---
- name: Install Required Packages
  become: yes
  command: "/usr/bin/dnf -y install python-dnf"
  when: ansible_distribution == "Fedora"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "apt-transport-https"
  - "python-apt"
  - "python-dev"
  when: ansible_distribution == "Ubuntu"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"
  - "ca-certificates"
  - "python-pip"

- name: Create Common Folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/{{base_software_directory}}"
  - "{{ansible_user_dir}}/{{base_download_directory}}"

