---
- name: Create Common Folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/{{base_software_directory}}"
  - "{{ansible_user_dir}}/{{base_download_directory}}"

- name: Activate Extra Packages for Enterprise Linux (EPEL)
  become: yes
  yum:
      name: "http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm"
      state: present
  when: ansible_distribution == "RedHat"

- name: Download PIP
  become: no
  get_url:
      url: "https://bootstrap.pypa.io/get-pip.py"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/get-pip.py"
      mode: 0554
  when: ansible_distribution == "CentOS"

- name: Run PIP Installer
  become: yes
  command: "python {{ansible_user_dir}}/{{base_download_directory}}/get-pip.py"
  args:
      creates: "/usr/bin/pip"
  when: ansible_distribution == "CentOS"

- name: Install Required Packages
  become: yes
  command: "/usr/bin/dnf -y install python-dnf"
  when: ansible_distribution == "Fedora"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "apt-transport-https"
  - "python-apt"
  - "python-dev"
  when: ansible_distribution == "Ubuntu"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "python-pip"
  when: ansible_distribution != "CentOS"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"
  - "ca-certificates"
