---
# without this seemly useless call, the ansible_user_directory does not get set properly
- name: Gather Facts
  setup:
      gather_timeout: 10

- name: Create Common Folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  loop:
  - "{{ansible_user_dir}}/{{base_software_directory}}"
  - "{{ansible_user_dir}}/{{base_download_directory}}"
  - "{{ansible_user_dir}}/Desktop"

- name: Activate Extra Packages for Enterprise Linux (EPEL)
  become: yes
  yum:
      name: "http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm"
      state: present
  when: ansible_distribution == "RedHat"

- name: Download PIP
  become: no
  get_url:
      url: "https://bootstrap.pypa.io/get-pip.py"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/get-pip.py"
      mode: 0554
  when: ansible_distribution == "CentOS"

- name: Run PIP Installer
  become: yes
  command: "python {{ansible_user_dir}}/{{base_download_directory}}/get-pip.py"
  args:
      creates: "/usr/bin/pip"
  when: ansible_distribution == "CentOS"

- name: Install Required Packages
  become: yes
  command: "/usr/bin/dnf -y install python-dnf"
  when: ansible_distribution == "Fedora"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  loop:
  - "apt-transport-https"
  - "python-apt"
  - "python-dev"
  when: ansible_distribution == "UbuntuXXXX"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  loop:
  - "python-pip"
  when: ansible_distribution == "never"
  #when: ansible_distribution != "CentOS"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  loop:
  - "curl"
  - "ca-certificates"
  - "unzip"
